# Generated by Django 5.1.1 on 2024-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
