# Generated by Django 5.1.1 on 2024-11-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_foo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
