# Generated by Django 5.1.1 on 2024-11-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_comment_options_rename_text_comment_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='image_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
